### ISSUE TITLE
Simplify configuration required to upload maven artifacts

### ISSUE THREAD

**Issue by a-buck** [drone-plugins/drone-artifactory#6]
Hi there, 

I was wondering if we could simplify the use of the artifactory plugin for uploading maven artifacts. With maven I could run:

`mvn deploy`

Maven would look at the pom, build the jar and upload the pom.xml and jar to artifactory.

With the artifactory plugin, I have to specify:
```
artifactory:
      url: my_companies_artifactory.com
      username: $$username
      password: $$password
      pom: pom.xml
      force_upload: true
      files:
        - pom.xml
        - target/*.jar
```
Could the plugin be updated so theoretically all that is required is:
```
artifactory:
      url: my_companies_artifactory.com
      username: $$username
      password: $$password
      pom: pom.xml
      force_upload: true
```

or if the jar is packaged to a non standard location
 perhaps:

```
artifactory:
      url: my_companies_artifactory.com
      username: $$username
      password: $$password
      pom: pom.xml
      force_upload: true
      jar: target/custom_directory/executable.jar

```
This would reduce the risk of anyone forgetting to upload the pom.xml along with the artifact as well as making it easier to use.

I would be happy to have a go at implementing this if you think it's a worthwhile thing to do.
